# Generated by Django 3.2.4 on 2021-06-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workcalendar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='EmployeeName',
        ),
    ]
