# Generated by Django 3.2.4 on 2021-06-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workcalendar', '0003_rename_title_task_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Work',
            new_name='Task',
        ),
    ]
