# Generated by Django 3.2.4 on 2021-06-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workcalendar', '0004_rename_work_task_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Task',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='EmployeeName',
            new_name='user',
        ),
    ]
