# Generated by Django 3.2.4 on 2021-06-26 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workcalendar', '0005_auto_20210626_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='create',
            new_name='Create',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='EmployeeName',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='Task',
        ),
    ]
